version: '3.3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    depends_on:
      - app
      - redis
